Fix NPE when attempting to use LDAP to authorize users for cas-management
apereo/cas-management pull request #245
Opened 2022-08-28 01:35 UTC by dmalia1

Moved to 6.6 branch.

I'm not aware of any issue numbers with this.

This change fixes a NPE when attempting to use ldap for authorization to cas-management.

The LdapUtils.newLdaptiveSearchOperation method doesn't set the LDAP connection factory, and thus when
the SearchOperation is executed, a NPE is thrown when it attempts to establish the connection.

There shouldn't be any side effects as this isn't updating the LDAPUtils, class, though its probable the fix should be made there, but that also lives in the cas repo, and not the cas-management repo.

There shouldn't be any changes to configuration, and testing involves including the module, and configuring the cas-management application to use authz via ldap.

This appears at the surface level to be a problem in the 6.4.x and 6.3.x branches as well.. I'm not sure if those branches are still receiving updates or not.

2022-08-31 04:00 UTC, mmoayyed requested changes

2022-08-31 04:00 UTC, mmoayyed commented on config/cas-mgmt-config-authz-ldap/src/main/java/org/apereo/cas/mgmt/config/CasManagementLdapAuthorizationConfiguration.java
> +        SearchOperation operation = LdapUtils.newLdaptiveSearchOperation(ldapAuthz.getBaseDn(), ldapAuthz.getSearchFilter(),
```suggestion
        val operation = LdapUtils.newLdaptiveSearchOperation(ldapAuthz.getBaseDn(), ldapAuthz.getSearchFilter(),
```

2022-08-31 04:00 UTC, mmoayyed commented on config/cas-mgmt-config-authz-ldap/src/main/java/org/apereo/cas/mgmt/config/CasManagementLdapAuthorizationConfiguration.java
> +        SearchOperation operation = LdapUtils.newLdaptiveSearchOperation(ldapAuthz.getGroupBaseDn(), ldapAuthz.getGroupFilter(),
```suggestion
        val operation = LdapUtils.newLdaptiveSearchOperation(ldapAuthz.getGroupBaseDn(), ldapAuthz.getGroupFilter(),
```

2022-09-02 17:55 UTC, dmalia1 commented on config/cas-mgmt-config-authz-ldap/src/main/java/org/apereo/cas/mgmt/config/CasManagementLdapAuthorizationConfiguration.java
> +        SearchOperation operation = LdapUtils.newLdaptiveSearchOperation(ldapAuthz.getBaseDn(), ldapAuthz.getSearchFilter(),
I merged these

2022-09-03 04:44 UTC, merged